# Generated by Django 6.0.2 on 2026-02-23 14:32

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import modelsearch.index
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='Optional; auto-generated from title if left blank.', unique=True)),
                ('client_or_org', models.CharField(blank=True, help_text='Client, organization, or stakeholder this work was for.', max_length=255)),
                ('brand_or_campaign', models.CharField(blank=True, help_text='Brand, product, campaign, or initiative name.', max_length=255)),
                ('date_start', models.DateField(blank=True, help_text='When the work began.', null=True)),
                ('date_end', models.DateField(blank=True, help_text='When the work ended.', null=True)),
                ('location', models.CharField(blank=True, help_text='Geographic scope (e.g. "UK / US / Global").', max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('publishable', 'Publishable'), ('sensitive', 'Sensitive')], default='draft', help_text='Workflow status for inclusion readiness.', max_length=20)),
                ('confidentiality', models.CharField(choices=[('public', 'Public'), ('anonymised', 'Anonymised'), ('private', 'Private')], default='public', help_text='Content sensitivity and privacy level.', max_length=20)),
                ('one_liner', models.TextField(blank=True, help_text='One or two sentence summary of the case.')),
                ('objective', models.TextField(help_text='What success meant for this case.')),
                ('audience', models.TextField(blank=True, help_text='Who this was for and why they mattered.')),
                ('constraints', models.TextField(blank=True, help_text='Known restrictions: time, budget, legal, platform, etc.')),
                ('strategy', models.TextField(help_text='The strategy used to solve the objective.')),
                ('creative_direction', models.TextField(blank=True, help_text='Narrative/visual direction and creative rationale.')),
                ('production_and_tooling', models.TextField(blank=True, help_text='Production process and tools/workflows used.')),
                ('delivery_and_distribution', models.TextField(blank=True, help_text='How work was shipped and distributed.')),
                ('my_contribution', models.TextField(help_text='Your explicit ownership and decision-making responsibilities.')),
                ('team_and_partners', models.TextField(blank=True, help_text='Internal team, partners, agencies, and collaborators.')),
                ('results_summary', models.TextField(blank=True, help_text='Narrative summary of impact and outcomes.')),
                ('what_worked', models.TextField(blank=True, help_text='What proved effective and why.')),
                ('what_id_do_differently', models.TextField(blank=True, help_text='Retrospective improvements you would make next time.')),
                ('spend_currency', models.CharField(choices=[('GBP', 'GBP'), ('USD', 'USD'), ('EUR', 'EUR'), ('Other', 'Other')], default='GBP', help_text='Currency used for spend estimates.', max_length=10)),
                ('spend_amount_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum spend estimate.', max_digits=12, null=True)),
                ('spend_amount_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum spend estimate.', max_digits=12, null=True)),
                ('spend_notes', models.TextField(blank=True, help_text='Assumptions (e.g. "approx, excludes production").')),
                ('proof_links', models.TextField(blank=True, help_text='One URL per line that supports this case.')),
                ('press_mentions', models.TextField(blank=True, help_text='One citation or link per line.')),
                ('notes_private', models.TextField(blank=True, help_text='Internal notes excluded from export by default.')),
                ('sort_date', models.DateField(blank=True, help_text='Admin sorting date. Defaults to end date, then start date.', null=True)),
            ],
            options={
                'ordering': ['-sort_date', '-date_end', '-date_start', 'title'],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='CaseMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('metric_name', models.CharField(help_text='Metric label (e.g. "ROAS", "Reach", "Revenue/day").', max_length=255)),
                ('value', models.CharField(help_text='Metric value, allowing flexible units (e.g. "ROAS 3.2", "4.5m users").', max_length=255)),
                ('timeframe', models.CharField(blank=True, help_text='Measurement period (e.g. "6 weeks", "Q1 2025").', max_length=255)),
                ('source', models.CharField(blank=True, help_text='Evidence source (e.g. "GA4", "Meta Ads", "Press").', max_length=255)),
                ('notes', models.CharField(blank=True, help_text='Extra metric context or caveats.', max_length=255)),
                ('case_study', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='casebook.casestudy')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CaseChannelSpend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('channel', models.CharField(choices=[('Meta', 'Meta'), ('Google', 'Google'), ('TikTok', 'TikTok'), ('X', 'X'), ('LinkedIn', 'LinkedIn'), ('Email', 'Email'), ('Organic Social', 'Organic Social'), ('Other', 'Other')], default='Other', help_text='Channel where spend occurred.', max_length=30)),
                ('spend_currency', models.CharField(choices=[('GBP', 'GBP'), ('USD', 'USD'), ('EUR', 'EUR'), ('Other', 'Other')], default='GBP', help_text='Currency for this channel spend amount.', max_length=10)),
                ('spend_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Spend amount for this channel segment.', max_digits=12, null=True)),
                ('dates', models.CharField(blank=True, help_text='Date label (e.g. "Jan-Mar 2025").', max_length=255)),
                ('notes', models.CharField(blank=True, help_text='Extra context for this spend item.', max_length=255)),
                ('case_study', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_spend', to='casebook.casestudy')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CaseAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('asset_type', models.CharField(choices=[('ad_screenshot', 'Ad Screenshot'), ('creative', 'Creative'), ('dashboard', 'Dashboard'), ('press', 'Press'), ('video_still', 'Video still'), ('other', 'Other')], default='other', help_text='Asset category for filtering and export context.', max_length=30)),
                ('caption', models.TextField(blank=True, help_text='Context or explanation for this asset.')),
                ('platform', models.CharField(blank=True, help_text='Source platform (e.g. "Meta", "Google", "TikTok").', max_length=100)),
                ('format', models.CharField(blank=True, help_text='Media format (e.g. "1:1", "9:16", "16:9", "carousel").', max_length=100)),
                ('date', models.DateField(blank=True, help_text='Date represented by this asset, if relevant.', null=True)),
                ('is_hero', models.BooleanField(default=False, help_text='Mark as the primary visual for this case (single hero only).')),
                ('alt_text', models.CharField(blank=True, help_text='Accessibility description for the image.', max_length=255)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
                ('case_study', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='casebook.casestudy')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CaseStudyTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='casebook.casestudy')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='casestudy',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='casebook.CaseStudyTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
