# Generated by Django 6.0.2 on 2026-02-23 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casebook', '0001_initial'),
        ('wagtaildocs', '0014_alter_document_file_size'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casestudy',
            name='notes_private',
        ),
        migrations.AddField(
            model_name='caseasset',
            name='video',
            field=models.ForeignKey(blank=True, help_text='Optional uploaded video document.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtaildocs.document'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='notes',
            field=models.TextField(blank=True, help_text='Public portfolio notes and context.'),
        ),
        migrations.AlterField(
            model_name='caseasset',
            name='asset_type',
            field=models.CharField(choices=[('ad_screenshot', 'Ad Screenshot'), ('creative', 'Creative'), ('dashboard', 'Dashboard'), ('press', 'Press'), ('video', 'Video'), ('other', 'Other')], default='other', help_text='Asset category for filtering and export context.', max_length=30),
        ),
        migrations.AlterField(
            model_name='caseasset',
            name='date',
            field=models.CharField(blank=True, help_text='Flexible date text for this asset (e.g. "January 2024").', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='caseasset',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='casemetric',
            name='metric_name',
            field=models.CharField(blank=True, help_text='Metric label (e.g. "ROAS", "Reach", "Revenue/day").', max_length=255),
        ),
        migrations.AlterField(
            model_name='casemetric',
            name='value',
            field=models.CharField(blank=True, help_text='Metric value, allowing flexible units (e.g. "ROAS 3.2", "4.5m users").', max_length=255),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='confidentiality',
            field=models.CharField(blank=True, choices=[('public', 'Public'), ('anonymised', 'Anonymised'), ('private', 'Private')], default='public', help_text='Content sensitivity and privacy level.', max_length=20),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='date_end',
            field=models.CharField(blank=True, help_text='Flexible end date text (e.g. "2024", "March 2024", "Q2 2024").', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='date_start',
            field=models.CharField(blank=True, help_text='Flexible start date text (e.g. "2024", "January 2024", "Q1 2024").', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='my_contribution',
            field=models.TextField(blank=True, help_text='Your explicit ownership and decision-making responsibilities.'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='objective',
            field=models.TextField(blank=True, help_text='What success meant for this case.'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='sort_date',
            field=models.CharField(blank=True, help_text='Optional sortable date label (e.g. "January 2024", "2024"). Defaults to end/start text.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('publishable', 'Publishable'), ('sensitive', 'Sensitive')], default='draft', help_text='Workflow status for inclusion readiness.', max_length=20),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='strategy',
            field=models.TextField(blank=True, help_text='The strategy used to solve the objective.'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='title',
            field=models.CharField(blank=True, help_text='Campaign title. Optional for early drafts.', max_length=255),
        ),
    ]
