# Generated by Django 6.0.2 on 2026-02-23 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casebook', '0002_remove_casestudy_notes_private_caseasset_video_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='casestudy',
            name='client_or_org',
        ),
        migrations.RemoveField(
            model_name='casestudy',
            name='confidentiality',
        ),
        migrations.RemoveField(
            model_name='casestudy',
            name='status',
        ),
        migrations.AddField(
            model_name='casestudy',
            name='sector',
            field=models.ForeignKey(blank=True, help_text='Industry sector for this campaign.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_studies', to='casebook.industry'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Client / organization this campaign belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_studies', to='casebook.organization'),
        ),
    ]
